# SPRING settings
spring:
  application:
    name: resale-service  # application name
  # DB settings
  datasource:
    url: jdbc:postgresql://localhost:5432/resale_db
    username: resale_owner
    password: ShowMeTheMoney511
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # Hibernate settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: ${app.upload.max-size}
      max-request-size: 15MB
      file-size-threshold: 2KB

# Server port, run by default
server:
  port: 8080

# Logger settings
logging:
  level:
    org.hibernate.tool.schema: DEBUG
    org.springframework.security: DEBUG


app:
  upload:
    max-size: 10485760  #byte (10MB)
    allowed-types: jpg, jpeg, png, webp
    main-dir: resale_images
    ads-dir: ads_images
    avatars-dir: avatars_images
  images:
    base-url: /images/
    cache-period: 1800 #seconds (30min)
  security:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    whitelist:
      - "/login"
      - "/register"
      - "/images/**"
      - "/swagger-resources/**"
      - "/swagger-ui.html"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
      - "/webjars/**"
    allowed-headers:
      - "Authorization"
      - "Content-Type"
      - "X-Requested-With"

